using System;
using System.Collections.Generic;
using System.Linq;

namespace SpawnDev.EBML.Matroska
{
    public class MatroskaSchema : EBMLSchema<MatroskaId>
    {
        /// <summary>
        /// Schema DocType
        /// </summary>
        public override string DocType { get; } = "matroska";
        /// <summary>
        /// The element ids that a cluster can contain. Used when detecting the end of a cluster.
        /// </summary>
        static List<MatroskaId> ClusterChildIds = new List<MatroskaId>
        {
            MatroskaId.Timecode,
            MatroskaId.Position,
            MatroskaId.PrevSize,
            MatroskaId.SimpleBlock,
            MatroskaId.BlockGroup,
            MatroskaId.Void,
        };
        /// <summary>
        /// The element ids that a segment can contain. Used when detecting the end of a segment.
        /// </summary>
        static List<MatroskaId> SegmentChildIds = new List<MatroskaId>
        {
            MatroskaId.SeekHead,
            MatroskaId.Info,
            MatroskaId.Tracks,
            MatroskaId.Chapters,
            MatroskaId.Cluster,
            MatroskaId.Cues,
            MatroskaId.Attachments,
            MatroskaId.Tags,
            MatroskaId.Void,
        };
        /// <summary>
        /// Used when trying to determine if an element is a child of an element of unknown size
        /// </summary>
        /// <param name="parentIdChain"></param>
        /// <param name="childElementId"></param>
        /// <returns></returns>
        public override bool ValidChildCheck(MatroskaId[] parentIdChain, MatroskaId childElementId)
        {
            switch (parentIdChain.Last())
            {
                case MatroskaId.Segment: return SegmentChildIds.Contains(childElementId);
                case MatroskaId.Cluster: return ClusterChildIds.Contains(childElementId);
            }
            return false;
        }
        /// <summary>
        /// Returns the type to be used for the given elementId, or null if unknown.
        /// </summary>
        /// <param name="elementId"></param>
        /// <returns></returns>
        public override Type? GetElementType(MatroskaId elementId)
        {
            return ElementTypeMap.TryGetValue(elementId, out var ret) ? ret : null;
        }
        /// <summary>
        /// ElementIds mapped to the type that will be used to represent the specified element
        /// </summary>
        public static Dictionary<MatroskaId, Type> ElementTypeMap { get; } = new Dictionary<MatroskaId, Type>
        {
            { MatroskaId.SignatureSlot, typeof(MasterElement) },
            { MatroskaId.SignatureAlgo, typeof(UintElement) },
            { MatroskaId.SignatureHash, typeof(UintElement) },
            { MatroskaId.SignaturePublicKey, typeof(BinaryElement) },
            { MatroskaId.Signature, typeof(BinaryElement) },
            { MatroskaId.SignatureElements, typeof(MasterElement) },
            { MatroskaId.SignatureElementList, typeof(MasterElement) },
            { MatroskaId.SignedElement, typeof(BinaryElement) },
            { MatroskaId.Segment, typeof(MasterElement) },
            { MatroskaId.SeekHead, typeof(MasterElement) },
            { MatroskaId.Seek, typeof(MasterElement) },
            { MatroskaId.SeekID, typeof(BinaryElement) },
            { MatroskaId.SeekPosition, typeof(UintElement) },
            { MatroskaId.Info, typeof(MasterElement) },
            { MatroskaId.SegmentUID, typeof(BinaryElement) },
            { MatroskaId.SegmentFilename, typeof(StringElement) },
            { MatroskaId.PrevUID, typeof(BinaryElement) },
            { MatroskaId.PrevFilename, typeof(StringElement) },
            { MatroskaId.NextUID, typeof(BinaryElement) },
            { MatroskaId.NextFilename, typeof(StringElement) },
            { MatroskaId.SegmentFamily, typeof(BinaryElement) },
            { MatroskaId.ChapterTranslate, typeof(MasterElement) },
            { MatroskaId.ChapterTranslateEditionUID, typeof(UintElement) },
            { MatroskaId.ChapterTranslateCodec, typeof(UintElement) },
            { MatroskaId.ChapterTranslateID, typeof(BinaryElement) },
            { MatroskaId.TimecodeScale, typeof(UintElement) },
            { MatroskaId.Duration, typeof(FloatElement) },
            { MatroskaId.DateUTC, typeof(DateElement) },
            { MatroskaId.Title, typeof(StringElement) },
            { MatroskaId.MuxingApp, typeof(UTF8StringElement) },
            { MatroskaId.WritingApp, typeof(StringElement) },
            { MatroskaId.Cluster, typeof(MasterElement) },
            { MatroskaId.Timecode, typeof(UintElement) },
            { MatroskaId.SilentTracks, typeof(MasterElement) },
            { MatroskaId.SilentTrackNumber, typeof(UintElement) },
            { MatroskaId.Position, typeof(UintElement) },
            { MatroskaId.PrevSize, typeof(UintElement) },
            { MatroskaId.SimpleBlock, typeof(SimpleBlockElement) },
            { MatroskaId.BlockGroup, typeof(MasterElement) },
            { MatroskaId.Block, typeof(BlockElement) },
            { MatroskaId.BlockVirtual, typeof(BinaryElement) },
            { MatroskaId.BlockAdditions, typeof(MasterElement) },
            { MatroskaId.BlockMore, typeof(MasterElement) },
            { MatroskaId.BlockAddID, typeof(UintElement) },
            { MatroskaId.BlockAdditional, typeof(BinaryElement) },
            { MatroskaId.BlockDuration, typeof(UintElement) },
            { MatroskaId.ReferencePriority, typeof(UintElement) },
            { MatroskaId.ReferenceBlock, typeof(IntElement) },
            { MatroskaId.ReferenceVirtual, typeof(IntElement) },
            { MatroskaId.CodecState, typeof(BinaryElement) },
            { MatroskaId.DiscardPadding, typeof(IntElement) },
            { MatroskaId.Slices, typeof(MasterElement) },
            { MatroskaId.TimeSlice, typeof(MasterElement) },
            { MatroskaId.LaceNumber, typeof(UintElement) },
            { MatroskaId.FrameNumber, typeof(UintElement) },
            { MatroskaId.BlockAdditionID, typeof(UintElement) },
            { MatroskaId.Delay, typeof(UintElement) },
            { MatroskaId.SliceDuration, typeof(UintElement) },
            { MatroskaId.ReferenceFrame, typeof(MasterElement) },
            { MatroskaId.ReferenceOffset, typeof(UintElement) },
            { MatroskaId.ReferenceTimeCode, typeof(UintElement) },
            { MatroskaId.EncryptedBlock, typeof(BinaryElement) },
            { MatroskaId.Tracks, typeof(MasterElement) },
            { MatroskaId.TrackEntry, typeof(TrackEntryElement) },
            { MatroskaId.TrackNumber, typeof(UintElement) },
            { MatroskaId.TrackUID, typeof(UintElement) },
            { MatroskaId.TrackType, typeof(UintElement) },
            { MatroskaId.FlagEnabled, typeof(UintElement) },
            { MatroskaId.FlagDefault, typeof(UintElement) },
            { MatroskaId.FlagForced, typeof(UintElement) },
            { MatroskaId.FlagLacing, typeof(UintElement) },
            { MatroskaId.MinCache, typeof(UintElement) },
            { MatroskaId.MaxCache, typeof(UintElement) },
            { MatroskaId.DefaultDuration, typeof(UintElement) },
            { MatroskaId.DefaultDecodedFieldDuration, typeof(UintElement) },
            { MatroskaId.TrackTimecodeScale, typeof(FloatElement) },
            { MatroskaId.TrackOffset, typeof(IntElement) },
            { MatroskaId.MaxBlockAdditionID, typeof(UintElement) },
            { MatroskaId.Name, typeof(StringElement) },
            { MatroskaId.Language, typeof(StringElement) },
            { MatroskaId.CodecID, typeof(StringElement) },
            { MatroskaId.CodecPrivate, typeof(BinaryElement) },
            { MatroskaId.CodecName, typeof(StringElement) },
            { MatroskaId.AttachmentLink, typeof(UintElement) },
            { MatroskaId.CodecSettings, typeof(StringElement) },
            { MatroskaId.CodecInfoURL, typeof(StringElement) },
            { MatroskaId.CodecDownloadURL, typeof(StringElement) },
            { MatroskaId.CodecDecodeAll, typeof(UintElement) },
            { MatroskaId.TrackOverlay, typeof(UintElement) },
            { MatroskaId.CodecDelay, typeof(UintElement) },
            { MatroskaId.SeekPreRoll, typeof(UintElement) },
            { MatroskaId.TrackTranslate, typeof(MasterElement) },
            { MatroskaId.TrackTranslateEditionUID, typeof(UintElement) },
            { MatroskaId.TrackTranslateCodec, typeof(UintElement) },
            { MatroskaId.TrackTranslateTrackID, typeof(BinaryElement) },
            { MatroskaId.Video, typeof(MasterElement) },
            { MatroskaId.FlagInterlaced, typeof(UintElement) },
            { MatroskaId.StereoMode, typeof(UintElement) },
            { MatroskaId.AlphaMode, typeof(UintElement) },
            { MatroskaId.OldStereoMode, typeof(UintElement) },
            { MatroskaId.PixelWidth, typeof(UintElement) },
            { MatroskaId.PixelHeight, typeof(UintElement) },
            { MatroskaId.PixelCropBottom, typeof(UintElement) },
            { MatroskaId.PixelCropTop, typeof(UintElement) },
            { MatroskaId.PixelCropLeft, typeof(UintElement) },
            { MatroskaId.PixelCropRight, typeof(UintElement) },
            { MatroskaId.DisplayWidth, typeof(UintElement) },
            { MatroskaId.DisplayHeight, typeof(UintElement) },
            { MatroskaId.DisplayUnit, typeof(UintElement) },
            { MatroskaId.AspectRatioType, typeof(UintElement) },
            { MatroskaId.ColourSpace, typeof(BinaryElement) },
            { MatroskaId.GammaValue, typeof(FloatElement) },
            { MatroskaId.FrameRate, typeof(FloatElement) },
            { MatroskaId.Audio, typeof(MasterElement) },
            { MatroskaId.SamplingFrequency, typeof(FloatElement) },
            { MatroskaId.OutputSamplingFrequency, typeof(FloatElement) },
            { MatroskaId.Channels, typeof(UintElement) },
            { MatroskaId.ChannelPositions, typeof(BinaryElement) },
            { MatroskaId.BitDepth, typeof(UintElement) },
            { MatroskaId.TrackOperation, typeof(MasterElement) },
            { MatroskaId.TrackCombinePlanes, typeof(MasterElement) },
            { MatroskaId.TrackPlane, typeof(MasterElement) },
            { MatroskaId.TrackPlaneUID, typeof(UintElement) },
            { MatroskaId.TrackPlaneType, typeof(UintElement) },
            { MatroskaId.TrackJoinBlocks, typeof(MasterElement) },
            { MatroskaId.TrackJoinUID, typeof(UintElement) },
            { MatroskaId.TrickTrackUID, typeof(UintElement) },
            { MatroskaId.TrickTrackSegmentUID, typeof(BinaryElement) },
            { MatroskaId.TrickTrackFlag, typeof(UintElement) },
            { MatroskaId.TrickMasterTrackUID, typeof(UintElement) },
            { MatroskaId.TrickMasterTrackSegmentUID, typeof(BinaryElement) },
            { MatroskaId.ContentEncodings, typeof(MasterElement) },
            { MatroskaId.ContentEncoding, typeof(MasterElement) },
            { MatroskaId.ContentEncodingOrder, typeof(UintElement) },
            { MatroskaId.ContentEncodingScope, typeof(UintElement) },
            { MatroskaId.ContentEncodingType, typeof(UintElement) },
            { MatroskaId.ContentCompression, typeof(MasterElement) },
            { MatroskaId.ContentCompAlgo, typeof(UintElement) },
            { MatroskaId.ContentCompSettings, typeof(BinaryElement) },
            { MatroskaId.ContentEncryption, typeof(MasterElement) },
            { MatroskaId.ContentEncAlgo, typeof(UintElement) },
            { MatroskaId.ContentEncKeyID, typeof(BinaryElement) },
            { MatroskaId.ContentSignature, typeof(BinaryElement) },
            { MatroskaId.ContentSigKeyID, typeof(BinaryElement) },
            { MatroskaId.ContentSigAlgo, typeof(UintElement) },
            { MatroskaId.ContentSigHashAlgo, typeof(UintElement) },
            { MatroskaId.Cues, typeof(MasterElement) },
            { MatroskaId.CuePoint, typeof(MasterElement) },
            { MatroskaId.CueTime, typeof(UintElement) },
            { MatroskaId.CueTrackPositions, typeof(MasterElement) },
            { MatroskaId.CueTrack, typeof(UintElement) },
            { MatroskaId.CueClusterPosition, typeof(UintElement) },
            { MatroskaId.CueRelativePosition, typeof(UintElement) },
            { MatroskaId.CueDuration, typeof(UintElement) },
            { MatroskaId.CueBlockNumber, typeof(UintElement) },
            { MatroskaId.CueCodecState, typeof(UintElement) },
            { MatroskaId.CueReference, typeof(MasterElement) },
            { MatroskaId.CueRefTime, typeof(UintElement) },
            { MatroskaId.CueRefCluster, typeof(UintElement) },
            { MatroskaId.CueRefNumber, typeof(UintElement) },
            { MatroskaId.CueRefCodecState, typeof(UintElement) },
            { MatroskaId.Attachments, typeof(MasterElement) },
            { MatroskaId.AttachedFile, typeof(MasterElement) },
            { MatroskaId.FileDescription, typeof(UTF8StringElement) },
            { MatroskaId.FileName, typeof(UTF8StringElement) },
            { MatroskaId.FileMimeType, typeof(StringElement) },
            { MatroskaId.FileData, typeof(BinaryElement) },
            { MatroskaId.FileUID, typeof(UintElement) },
            { MatroskaId.FileReferral, typeof(BinaryElement) },
            { MatroskaId.FileUsedStartTime, typeof(UintElement) },
            { MatroskaId.FileUsedEndTime, typeof(UintElement) },
            { MatroskaId.Chapters, typeof(MasterElement) },
            { MatroskaId.EditionEntry, typeof(MasterElement) },
            { MatroskaId.EditionUID, typeof(UintElement) },
            { MatroskaId.EditionFlagHidden, typeof(UintElement) },
            { MatroskaId.EditionFlagDefault, typeof(UintElement) },
            { MatroskaId.EditionFlagOrdered, typeof(UintElement) },
            { MatroskaId.ChapterAtom, typeof(MasterElement) },
            { MatroskaId.ChapterUID, typeof(UintElement) },
            { MatroskaId.ChapterStringUID, typeof(StringElement) },
            { MatroskaId.ChapterTimeStart, typeof(UintElement) },
            { MatroskaId.ChapterTimeEnd, typeof(UintElement) },
            { MatroskaId.ChapterFlagHidden, typeof(UintElement) },
            { MatroskaId.ChapterFlagEnabled, typeof(UintElement) },
            { MatroskaId.ChapterSegmentUID, typeof(BinaryElement) },
            { MatroskaId.ChapterSegmentEditionUID, typeof(UintElement) },
            { MatroskaId.ChapterPhysicalEquiv, typeof(UintElement) },
            { MatroskaId.ChapterTrack, typeof(MasterElement) },
            { MatroskaId.ChapterTrackNumber, typeof(UintElement) },
            { MatroskaId.ChapterDisplay, typeof(MasterElement) },
            { MatroskaId.ChapString, typeof(StringElement) },
            { MatroskaId.ChapLanguage, typeof(StringElement) },
            { MatroskaId.ChapCountry, typeof(StringElement) },
            { MatroskaId.ChapProcess, typeof(MasterElement) },
            { MatroskaId.ChapProcessCodecID, typeof(UintElement) },
            { MatroskaId.ChapProcessPrivate, typeof(BinaryElement) },
            { MatroskaId.ChapProcessCommand, typeof(MasterElement) },
            { MatroskaId.ChapProcessTime, typeof(UintElement) },
            { MatroskaId.ChapProcessData, typeof(BinaryElement) },
            { MatroskaId.Tags, typeof(MasterElement) },
            { MatroskaId.Tag, typeof(MasterElement) },
            { MatroskaId.Targets, typeof(MasterElement) },
            { MatroskaId.TargetTypeValue, typeof(UintElement) },
            { MatroskaId.TargetType, typeof(StringElement) },
            { MatroskaId.TagTrackUID, typeof(UintElement) },
            { MatroskaId.TagEditionUID, typeof(UintElement) },
            { MatroskaId.TagChapterUID, typeof(UintElement) },
            { MatroskaId.TagAttachmentUID, typeof(UintElement) },
            { MatroskaId.SimpleTag, typeof(MasterElement) },
            { MatroskaId.TagName, typeof(UTF8StringElement) },
            { MatroskaId.TagLanguage, typeof(StringElement) },
            { MatroskaId.TagDefault, typeof(UintElement) },
            { MatroskaId.TagString, typeof(UTF8StringElement) },
            { MatroskaId.TagBinary, typeof(BinaryElement) },
        };
    }
}
